[workspace]
resolver = "2"
members = ["crates/mls", "crates/conformance", "crates/harness", "crates/ds", "crates/client", "crates/baselines", "crates/experiments", "crates/differential", "crates/wire", "crates/web"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[profile.release]
debug = 1

[profile.bench]
debug = 1
